import Head from "next/head";

import React, { useEffect, useState, useContext } from "react";
import { ToastContainer, toast } from "react-toastify";
import axios from "axios";

import { FiAlertCircle } from "react-icons/fi";
import { AiOutlineClose } from "react-icons/ai";

import Link from "next/link";
import { useSelector } from "react-redux";
import Testimonial from "./testimonial";

export default function Home() {
  const Data = useSelector((state) => state.userReducer.userData);
  console.log("==============>>>>>>>>>>>>>>>>", Data);
  const [closed, setClosed] = useState(false);
  return (
    <div>
      <Head>
        <title>Realback || Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/realback.png" />
      </Head>
      <div style={{ backgroundColor: "#000" }}>
        <ToastContainer />

        <section>
          <div className="container">
            <div className="row  ">
              {closed === false ? (
                <div
                  className="notification  col-md-12 "
                  style={{
                    backgroundColor: "rgb(16 16 16 / 81%)",
                    fontFamily: "sans-serif",
                    padding: 20,
                    textAlign: "center",
                    borderRadius: 10,
                    // marginTop: 50,
                    color: "#6b6b6b",
                  }}
                >
                  {" "}
                  <FiAlertCircle
                    size="25"
                    color="white"
                    style={{ marginRight: 10 }}
                  />
                  Welcome to Realback services we notify you that our services
                  only Available in Jaipur now
                  <AiOutlineClose
                    style={{
                      marginLeft: "auto",
                      float: "right",
                    }}
                    onClick={() => setClosed(true)}
                    color="white"
                    size="20"
                  />
                </div>
              ) : null}

              <div
                style={{
                  margin: "auto",
                  justifyContent: "center",
                  alignItems: "center",
                }}
                className="col-md-7 p-2 mt-5 "
              >
                <figure data-aos="fade-in ">
                  <img src="images/airpods.png" alt="" className="img-fluid" />
                </figure>
              </div>
              <div className="col-md-5 mt-5 ">
                <div style={{ padding: 20 }}>
                  <h1
                    style={{ color: "#fff", fontFamily: "unset" }}
                    className="gradtext"
                  >
                    Realback for your
                  </h1>
                  <h3 className="gradtext" style={{ color: "#fff" }}>
                    all devices solutions
                  </h3>
                  <p className="gradtext" style={{ color: "#fff" }}>
                    You can esaliy repair your elctronics devices with Realback
                    get your service Now!
                  </p>
                  <div className=" social-btns mt-5">
                    <Link href="/models/components/service">
                      <a
                        style={{
                          padding: 15,
                          backgroundColor: "#0070f3",
                          boxShadow: "0 4px 14px 0 rgb(0 118 255 / 39%)",
                        }}
                        className="app-btn blu flex vert  "
                      >
                        <span className="big-txt">Service</span>
                      </a>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* <div className="container">
          <div className="row">
            <div className="col-md-3">
              {" "}
              <img
                src="/images/sponsor1.png"
                title=""
                className="marqueelogo"
              />
            </div>
            <div className="col-md-3">
              <img
                src="/images/sponsor2.png"
                title=""
                className="marqueelogo"
              />
            </div>
            <div className="col-md-3">
              <img
                src="/images/sponsor3.png"
                title=""
                className="marqueelogo"
              />
            </div>
            <div className="col-md-3">
              <img
                src="/images/sponsor4.png"
                title=""
                className="marqueelogo"
              />
            </div>
          </div>
        </div> */}

        {/* <div className="logoMarqueeSection mt-5">
          <div className="container" id="logoMarqueeSection">
            <div className="default-content-container flex items-center">
              <div className="default-content-container-inner marquee-wrapper relative overflow-hidden inline-block">
                <div className="marquee" style={{ animationDuration: "57s" }}>
                  <a target="_blank">
                    <img
                      src="/images/sponsor1.png"
                      title=""
                      className="marqueelogo"
                    />
                  </a>
                  <a target="_blank">
                    <img
                      src="/images/sponsor2.png"
                      title=""
                      className="marqueelogo"
                    />
                  </a>
                  <a target="_blank">
                    <img
                      src="/images/sponsor3.png"
                      title=""
                      className="marqueelogo"
                    />
                  </a>
                  <a target="_blank">
                    <img
                      src="/images/sponsor4.png"
                      title=""
                      className="marqueelogo"
                    />
                  </a> */}

        {/* <a target="_blank">
                    <img
                      src="https://1000logos.net/wp-content/uploads/2018/09/Honor-logo.png"
                      title=""
                      className="marqueelogo"
                    />
                  </a>
                  <a target="_blank">
                    <img
                      src="https://upload.wikimedia.org/wikipedia/commons/b/bc/Realme-realme-_logo_box-RGB-01.png"
                      title=""
                      className="marqueelogo"
                    />
                  </a>
                  <a target="_blank">
                    <img
                      src="https://www.freepnglogos.com/uploads/xiaomi-png/xiaomi-logo-logos-marcas-8.png"
                      title=""
                      className="marqueelogo"
                    />
                  </a>
                  <a target="_blank">
                    <img
                      src="https://www.searchpng.com/wp-content/uploads/2019/01/vivo-Phone-logo.png"
                      title=""
                      className="marqueelogo"
                    />
                  </a> */}
        {/* <a target="_blank">
                    <img
                      src="https://www.freepnglogos.com/uploads/oppo-logo-png/oppo-green-logo-transparent-0.png"
                      title=""
                      className="marqueelogo"
                    />
                  </a>
                  <a target="_blank">
                    <img
                      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOXkMpw3xPGNNNto3lgm9Phz9jsfz80-AITBKiEpgL5ZuXy-It_5v5Ar2cVjXI-nwjFIY&usqp=CAU"
                      title=""
                      className="marqueelogo"
                    />
                  </a>
                  <a target="_blank">
                    <img
                      src="https://pngimg.com/uploads/sony_logo/sony_logo_PNG5.png"
                      title=""
                      className="marqueelogo"
                    />
                  </a>
                  <a target="_blank">
                    <img
                      src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/ASUS_Logo.svg/2560px-ASUS_Logo.svg.png"
                      title=""
                      className="marqueelogo"
                    />
                  </a> */}
        {/* <a target="_blank">
                  <img
                    src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Nokia_wordmark.svg/1024px-Nokia_wordmark.svg.png"
                    title=""
                    className="marqueelogo"
                  />
                </a> */}
        {/* </div>
              </div>
            </div>
          </div>
        </div> */}

        {/* <section className="mt-5">
          <div className="container">
            <div className="row">
              <div className="col-md-6 col-xl-4  ">
                <div style={{ margin: "auto" }}>
                  <div className="cardd ">
                    <img
                      src="images/realback.png"
                      alt="logo"
                      style={{ width: 50, height: 50 }}
                    />
                    <p style={{ float: "right" }}>23/12/2021</p>
                    <h2 className="card_title"></h2>
                    <p className="pricing">
                      1.32$<span className="small">/3 month</span>
                    </p>

                    <ul className="features">
                      <li>10% 0ff</li>
                      <li>Free delivery</li>
                      <li>Gift and rewards</li>
                      <li>Pay later amount below 4000</li>
                    </ul>

                    <Link href="/models/sachin" className="cta_btn">
                      <a>Buy Now</a>
                    </Link>
                  </div>
                </div>
              </div>
              <div className="col-md-6">
                <div>
                  <img src="card.webp" alt="23" className="img-fluid" />
                </div>
              </div>
            </div>
          </div>
        </section> */}

        <section style={{}}>
          <div className="container-fluid ">
            <div className="row  ">
              <div className="col-md-12 ">
                <div className="wrapper ">
                  <video autoplay="autoPlay" muted className="wrapper__video ">
                    <source type="video/mp4" src="images/App2.mp4" />
                  </video>
                </div>
                <div style={{ paddingLeft: 10 }}>
                  <h1
                    style={{
                      fontWeight: "bold",
                      color: "#fff",
                      textAlign: "center",
                    }}
                    className="gradtext"
                  >
                    Available on App Store
                  </h1>
                  <p
                    className="gradtext"
                    style={{ color: "#fff", textAlign: "center" }}
                  >
                    Download our App from App Store for both Android and IOS
                    platform soon.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* <Testimonial /> */}
      </div>
    </div>
  );
}
