import React from "react";
import Head from "next/head";
import { useDispatch } from "react-redux";
import { rootUser } from "../../actions";
import axios from "axios";



const Sachin = ({ userData }) => {
  console.log(userData);
  // const dispatch = useDispatch();
  // dispatch(rootUser(authUser));
  return (
    <div>
      <Head>
        <title>Sachin Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
{userData.map((u) =>{
  return (
    <>

    <h1>{u.title}</h1>
    <h2>{u.id}</h2>
    <p>{u.body}</p>
    </>
  )
})}

    </div>
  );
};

export default Sachin;


export async function getStaticProps(context) {

 const res = await axios.get('https://jsonplaceholder.typicode.com/posts')
   console.log(res);
  return {
    props: {

userData:res.data

    }
  };
}


// export const getServerSid = async (ctx) => {
  
//   const res = await axios.get("http://localhost:5000/api/rootUser", {
//     headers: ctx.req ? { cookie: ctx.req.headers.cookie } : undefined,
//   });

//   console.log(res.data);
//   return {
//     props: {
//       authUser: res.data,
//     },
//   };
// };

// export async function getServerSideProps() {

//   const res = await axios.get("https://jsonplaceholder.typicode.com/posts")
//   console.log("==================xxxxxxxxxx" , res);

//   return {
// props:{
//   res
// }

//   }
// }
